export enum Settings {
  BATCH_PROCESS_OPERATION_INTERVAL = 'BATCH_PROCESS_OPERATION_INTERVAL',
  BATCH_PROCESS_OPERATION_LIMIT = 'BATCH_PROCESS_OPERATION_LIMIT',
  BATCH_INSERT_OPERATION_INTERVAL = 'BATCH_INSERT_OPERATION_INTERVAL',
}
