FROM node:18-alpine as dependencies
RUN npm install -g pnpm

WORKDIR /app
ADD packages/config packages/config
ADD package.json pnpm-workspace.yaml ./
RUN pnpm install
RUN pnpm -r build

ADD packages/common packages/common
ADD packages/database packages/database
ADD packages/logger packages/logger
RUN pnpm install
RUN pnpm -r build

FROM dependencies as build
ARG APPLICATION

WORKDIR /app
ADD apps/${APPLICATION} apps/${APPLICATION}
RUN pnpm install
RUN pnpm -r build

FROM node:18-alpine
RUN npm install -g pnpm
ARG APPLICATION
WORKDIR /app

COPY --from=build /app/packages/common /app/packages/common
COPY --from=build /app/packages/config /app/packages/config
COPY --from=build /app/packages/database /app/packages/database
COPY --from=build /app/packages/logger /app/packages/logger
COPY --from=build /app/apps/${APPLICATION} ./apps/${APPLICATION}
COPY --from=build /app/package.json /app/pnpm-workspace.yaml ./
COPY --from=build /app/node_modules ./node_modules
WORKDIR /app/apps/${APPLICATION}
# start nest
ENTRYPOINT ["pnpm", "start:prod"]
# ENTRYPOINT ["tail", "-f","/dev/null"]