export enum UserOperationTypeEnum {
  MAKE_TRADEABLE = 'MAKE_TRADEABLE',
  MARKETPLACE_LISTING = 'MARKETPLACE_LISTING',
  MARKETPLACE_UPDATE = 'MARKETPLACE_UPDATE',
  MARKETPLACE_CANCEL = 'MARKETPLACE_CANCEL',
  MARKETPLACE_DEAL = 'MARKETPLACE_DEAL',
}

export enum UserOperationStatusEnum {
  IN_PROCESS = 'IN_PROCESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
