export enum AUTH_ERROR_CODES {
  // Общие
  UNKNOWN_ERROR = 'AUTH_000',
  INVALID_TOKEN = 'AUTH_001',
  SESSION_NOT_FOUND = 'AUTH_002',
  SESSION_EXPIRED = 'AUTH_003',
  INVALID_CREDENTIALS = 'AUTH_004',
  RATE_LIMIT_EXCEEDED = 'AUTH_005',
  SESSION_LIMIT_EXCEEDED = 'AUTH_006',
  USER_NOT_FOUND = 'AUTH_007',
  PERMISSION_DENIED = 'AUTH_008',
  // Сессии
  SESSION_CREATION_FAILED = 'AUTH_101',
  SESSION_TERMINATION_FAILED = 'AUTH_102',
  SESSIONS_TERMINATION_FAILED = 'AUTH_103',
  SESSIONS_DELETE_FAILED = 'AUTH_104',
  // Токены
  TOKEN_CREATION_FAILED = 'AUTH_201',
  TOKEN_REFRESH_FAILED = 'AUTH_202',
  TOKEN_VERIFICATION_FAILED = 'AUTH_203',
  // История/выборка
  SESSIONS_HISTORY_FAILED = 'AUTH_301',
  ACTIVE_SESSIONS_FAILED = 'AUTH_302',
  SESSIONS_UNTIL_DATE_FAILED = 'AUTH_303',
  // Аутентификация
  AUTHENTICATION_FAILED = 'AUTH_401',
  MISSING_CONFIRMATION_CODE = 'AUTH_402',
  INVALID_CONFIRMATION_CODE = 'AUTH_403',
  EXPIRED_CONFIRMATION_CODE = 'AUTH_404',
  // Accsess
  ACCESS_DENIED = 'AUTH_501',
}

export const AuthErrorMessages: Record<AUTH_ERROR_CODES, string> = {
  [AUTH_ERROR_CODES.UNKNOWN_ERROR]: 'Unknown error',
  [AUTH_ERROR_CODES.INVALID_TOKEN]: 'Invalid token',
  [AUTH_ERROR_CODES.SESSION_NOT_FOUND]: 'Session not found',
  [AUTH_ERROR_CODES.SESSION_EXPIRED]: 'Session expired',
  [AUTH_ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid credentials',
  [AUTH_ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [AUTH_ERROR_CODES.SESSION_LIMIT_EXCEEDED]: 'Session limit exceeded',
  [AUTH_ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [AUTH_ERROR_CODES.PERMISSION_DENIED]: 'Permission denied',
  [AUTH_ERROR_CODES.SESSION_CREATION_FAILED]: 'Session creation failed',
  [AUTH_ERROR_CODES.SESSION_TERMINATION_FAILED]: 'Session termination failed',
  [AUTH_ERROR_CODES.SESSIONS_TERMINATION_FAILED]: 'Sessions termination failed',
  [AUTH_ERROR_CODES.SESSIONS_DELETE_FAILED]: 'Sessions delete failed',
  [AUTH_ERROR_CODES.TOKEN_CREATION_FAILED]: 'Token creation failed',
  [AUTH_ERROR_CODES.TOKEN_REFRESH_FAILED]: 'Token refresh failed',
  [AUTH_ERROR_CODES.TOKEN_VERIFICATION_FAILED]: 'Token verification failed',
  [AUTH_ERROR_CODES.SESSIONS_HISTORY_FAILED]: 'Sessions history fetch failed',
  [AUTH_ERROR_CODES.ACTIVE_SESSIONS_FAILED]: 'Active sessions fetch failed',
  [AUTH_ERROR_CODES.SESSIONS_UNTIL_DATE_FAILED]:
    'Sessions until date fetch failed',
  [AUTH_ERROR_CODES.AUTHENTICATION_FAILED]: 'Authentication failed',
  [AUTH_ERROR_CODES.MISSING_CONFIRMATION_CODE]: 'Missing confirmation code',
  [AUTH_ERROR_CODES.INVALID_CONFIRMATION_CODE]: 'Invalid confirmation code',
  [AUTH_ERROR_CODES.EXPIRED_CONFIRMATION_CODE]: 'Confirmation code is expired',
  [AUTH_ERROR_CODES.ACCESS_DENIED]: 'Access denied',
};
